import { useEffect, useState } from 'react'
import { motion } from 'framer-motion'
import { CheckCircle2, Download, FileText, RotateCcw } from 'lucide-react'

import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { api } from '@/lib/api'

type PdfState = 'idle' | 'running' | 'done' | 'error'

/** Final stage: the upload is gone, the Investigation Report is ready to download.
 *  English is generated by the pipeline; Kannada generates on demand. */
export function ReportDone({ caseId, onReset }: { caseId: string; onReset: () => void }) {
  const [language, setLanguage] = useState<'en' | 'kn'>('en')
  const [state, setState] = useState<PdfState>('idle')
  const [error, setError] = useState('')

  useEffect(() => {
    if (!caseId) return
    setState('idle')
    setError('')
    api
      .reportPdfStatus(caseId, language)
      .then((s) => {
        if (s.status === 'done') setState('done')
        else if (s.status === 'running') {
          setState('running')
          void poll(language)
        }
      })
      .catch(() => {})
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [caseId, language])

  async function poll(lang: 'en' | 'kn') {
    for (;;) {
      await new Promise((r) => setTimeout(r, 3000))
      let s
      try {
        s = await api.reportPdfStatus(caseId, lang)
      } catch {
        continue
      }
      if (s.status === 'done') return setState('done')
      if (s.status === 'error') {
        setError(s.error || 'Report generation failed.')
        return setState('error')
      }
    }
  }

  async function generate() {
    setError('')
    setState('running')
    try {
      await api.runReportPdf(caseId, language)
      await poll(language)
    } catch (e) {
      setError(String(e))
      setState('error')
    }
  }

  return (
    <motion.div
      initial={{ opacity: 0, scale: 0.98, y: 8 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
      className="mx-auto max-w-2xl"
    >
      <Card className="p-6 text-center">
        <div className="mx-auto grid size-14 place-items-center rounded-full bg-green/15 text-green">
          <CheckCircle2 className="size-8" />
        </div>
        <h2 className="mt-4 font-display text-xl font-extrabold text-ink">Case processed</h2>
        <p className="mx-auto mt-1.5 max-w-md text-sm text-muted-foreground">
          The <b>Investigation Report</b> — a decision-support document with the money flow, suspicious accounts,
          fraud patterns and recommended priorities — is ready. It is an investigative analysis, not a court-ready
          or legal document.
        </p>

        {/* Language toggle */}
        <div className="mt-5 inline-flex overflow-hidden rounded-lg border border-line">
          {(['en', 'kn'] as const).map((lang) => (
            <button
              key={lang}
              onClick={() => setLanguage(lang)}
              className={`px-4 py-1.5 text-xs font-semibold ${language === lang ? 'bg-ink text-canvas' : 'bg-paper text-muted-foreground'}`}
            >
              {lang === 'en' ? 'English' : 'ಕನ್ನಡ'}
            </button>
          ))}
        </div>

        <div className="mt-4 flex flex-wrap items-center justify-center gap-2">
          {state === 'done' ? (
            <Button size="lg" asChild>
              <a href={api.reportPdfUrl(caseId, language)} target="_blank" rel="noreferrer">
                <Download className="size-4" /> Download Investigation Report (PDF)
              </a>
            </Button>
          ) : (
            <Button size="lg" onClick={generate} disabled={state === 'running'}>
              <FileText className="size-4" />
              {state === 'running' ? 'Generating…' : `Generate ${language === 'kn' ? 'Kannada' : 'English'} report`}
            </Button>
          )}
          <Button size="lg" variant="outline" onClick={onReset}>
            <RotateCcw className="size-4" /> Start new case
          </Button>
        </div>

        {state === 'running' && <p className="mt-3 text-xs text-muted-foreground">Rendering the report — narration and graphs take a moment.</p>}
        {state === 'error' && <p className="mt-3 text-xs text-red">{error}</p>}
      </Card>
    </motion.div>
  )
}
