"""Language labels and deterministic Kannada presentation helpers for reports."""

from __future__ import annotations

from typing import Any


SUPPORTED_LANGUAGES = {"en", "kn"}


def normalize_language(language: str | None) -> str:
    code = str(language or "en").strip().lower()
    if code in {"kannada", "ಕನ್ನಡ"}:
        return "kn"
    return code if code in SUPPORTED_LANGUAGES else "en"


LABELS: dict[str, dict[str, str]] = {
    "en": {
        "confidential_use": "Confidential · For Investigative Use",
        "report_title_html": "Financial<br>Investigation<br>Report",
        "prepared_by": "Prepared by:",
        "engine_name": "Survey Corps — Investigation Engine",
        "case_reference": "Case reference",
        "generated": "Generated",
        "cover_note": (
            "This report presents investigative leads based on transaction pattern analysis. "
            "It does not establish guilt — all findings should be independently verified before action."
        ),
        "toc": "Table of Contents",
        "case_reconstruction": "Case Reconstruction",
        "input_summary": "Input Summary",
        "analysis_summary": "Analysis Summary",
        "findings_by_account": "Findings by Account",
        "money_flow_graphs": "Money-Flow Graphs",
        "ai_flagged_leads": "AI-Flagged Leads",
        "final_summary": "Final Summary",
        "clusters": "Clusters",
        "connected_clusters": "Connected clusters",
        "isolated_clusters": "Isolated clusters",
        "highest_priority_account": "Highest-priority account",
        "cluster_score": "Cluster score",
        "members": "Members",
        "isolated_accounts_heading": "Accounts with no established connections in this case",
        "no_case_summary": "No case reconstruction summary was generated for this run.",
        "connected_cluster_fallback": "This connected account group was reconstructed from the money-flow graph and detector outputs.",
        "isolated_cluster_fallback": "This account was flagged individually without an established transactional link to another account in the case.",
        "source_account_id": "Source Account ID",
        "account_number": "Account Number",
        "account_holder": "Account Holder",
        "bank": "Bank",
        "ifsc": "IFSC",
        "accounts_analysed": "Accounts analysed",
        "transactions": "Transactions",
        "counterparties_resolved": "Counterparties resolved",
        "accounts_flagged": "Accounts flagged",
        "rank": "Rank",
        "score": "Score",
        "supporting_transactions": "Supporting transactions",
        "date": "Date",
        "type": "Type",
        "amount": "Amount",
        "counterparty": "Counterparty",
        "reference": "Reference",
        "assessment": "Assessment",
        "strong_pattern_types": "strong pattern type(s)",
        "distinct_patterns": "distinct pattern(s)",
        "evidence": "evidence",
        "no_accounts_flagged": "No accounts met the criteria for investigative flagging in this run.",
        "graph_missing": "Insufficient connected transactions to render this graph for this run.",
        "lead_note": "Statistical leads — not yet matched to a known pattern, recommended for manual review.",
        "lead": "lead",
        "key_concern": "Key Concern",
        "score_legend": "Score legend",
        "score_range": "Score Range",
        "what_it_means": "What It Means",
        "footer_prefix": "Generated by the",
        "footer_suffix": "All findings are investigative leads requiring independent verification.",
        "report_basis_suffix": "transactions, spanning",
        "report_basis_to": "to",
        "account_s": "account(s)",
        "edge_s": "edge(s)",
        "more": "more",
        "and": "and",
        "no_graph_connections": "No accounts met the criteria for investigative flagging in this run.",
        "case_narrative": "Case Narrative",
        "case_narrative_intro": "In brief, for the investigating officer:",
        "total_moved_label": "Total money moved",
        "into_network_label": "Entered suspect network",
        "first_investigation_target": "Investigate first",
        "data_security": "Data Security & Method (Appendix)",
        "what_stays_local": "What stays on this machine",
        "what_leaves_machine": "What is sent to an external service",
        "llm_usage_label": "Language-model calls this run",
        "prime_suspects": "Prime Suspects — Investigate First",
        "prime_suspects_intro": "The highest-priority accounts in this case, in order:",
        "priority_note_a": "Showing the",
        "priority_note_b": "highest-priority accounts in full detail. All",
        "priority_note_c": "flagged accounts are ranked in the Final Summary table.",
    },
    "kn": {
        "confidential_use": "ಗೌಪ್ಯ · ತನಿಖಾ ಬಳಕೆಗೆ ಮಾತ್ರ",
        "report_title_html": "ಹಣಕಾಸು<br>ತನಿಖಾ<br>ವರದಿ",
        "prepared_by": "ಸಿದ್ಧಪಡಿಸಿದವರು:",
        "engine_name": "ಸರ್ವೇ ಕಾರ್ಪ್ಸ್ — ತನಿಖಾ ಎಂಜಿನ್",
        "case_reference": "ಪ್ರಕರಣ ಉಲ್ಲೇಖ",
        "generated": "ರಚಿಸಿದ ಸಮಯ",
        "cover_note": (
            "ಈ ವರದಿ ವ್ಯವಹಾರ ಮಾದರಿ ವಿಶ್ಲೇಷಣೆಯ ಆಧಾರದ ಮೇಲೆ ತನಿಖಾ ಸುಳಿವುಗಳನ್ನು ನೀಡುತ್ತದೆ. "
            "ಇದು ಅಪರಾಧವನ್ನು ಸ್ಥಾಪಿಸುವುದಿಲ್ಲ; ಯಾವುದೇ ಕ್ರಮಕ್ಕೂ ಮೊದಲು ಎಲ್ಲಾ ಕಂಡುಹಿಡಿಕೆಗಳನ್ನು ಸ್ವತಂತ್ರವಾಗಿ ಪರಿಶೀಲಿಸಬೇಕು."
        ),
        "toc": "ಪರಿವಿಡಿ",
        "case_reconstruction": "ಪ್ರಕರಣ ಮರುರಚನೆ",
        "input_summary": "ಇನ್‌ಪುಟ್ ಸಾರಾಂಶ",
        "analysis_summary": "ವಿಶ್ಲೇಷಣಾ ಸಾರಾಂಶ",
        "findings_by_account": "ಖಾತೆವಾರು ಕಂಡುಹಿಡಿಕೆಗಳು",
        "money_flow_graphs": "ಹಣದ ಹರಿವು ಗ್ರಾಫ್‌ಗಳು",
        "ai_flagged_leads": "AI ಗುರುತಿಸಿದ ಸುಳಿವುಗಳು",
        "final_summary": "ಅಂತಿಮ ಸಾರಾಂಶ",
        "clusters": "ಕ್ಲಸ್ಟರ್‌ಗಳು",
        "connected_clusters": "ಸಂಪರ್ಕಿತ ಕ್ಲಸ್ಟರ್‌ಗಳು",
        "isolated_clusters": "ಪ್ರತ್ಯೇಕ ಕ್ಲಸ್ಟರ್‌ಗಳು",
        "highest_priority_account": "ಅತ್ಯುನ್ನತ ಆದ್ಯತೆಯ ಖಾತೆ",
        "cluster_score": "ಕ್ಲಸ್ಟರ್ ಅಂಕ",
        "members": "ಸದಸ್ಯರು",
        "isolated_accounts_heading": "ಈ ಪ್ರಕರಣದಲ್ಲಿ ಸ್ಥಾಪಿತ ಸಂಪರ್ಕವಿಲ್ಲದ ಖಾತೆಗಳು",
        "no_case_summary": "ಈ ರನ್‌ಗೆ ಪ್ರಕರಣ ಮರುರಚನೆ ಸಾರಾಂಶ ರಚಿಸಲಾಗಿಲ್ಲ.",
        "connected_cluster_fallback": "ಈ ಸಂಪರ್ಕಿತ ಖಾತೆ ಗುಂಪು ಹಣದ ಹರಿವು ಗ್ರಾಫ್ ಮತ್ತು ಡಿಟೆಕ್ಟರ್ ಫಲಿತಾಂಶಗಳಿಂದ ಮರುರಚಿಸಲಾಗಿದೆ.",
        "isolated_cluster_fallback": "ಈ ಖಾತೆ ಪ್ರಕರಣದ ಇತರ ಖಾತೆಗಳೊಂದಿಗೆ ಸ್ಥಾಪಿತ ವ್ಯವಹಾರ ಸಂಪರ್ಕವಿಲ್ಲದೆ ಪ್ರತ್ಯೇಕವಾಗಿ ಗುರುತಿಸಲಾಗಿದೆ.",
        "source_account_id": "ಮೂಲ ಖಾತೆ ID",
        "account_number": "ಖಾತೆ ಸಂಖ್ಯೆ",
        "account_holder": "ಖಾತೆದಾರ",
        "bank": "ಬ್ಯಾಂಕ್",
        "ifsc": "IFSC",
        "accounts_analysed": "ವಿಶ್ಲೇಷಿಸಿದ ಖಾತೆಗಳು",
        "transactions": "ವ್ಯವಹಾರಗಳು",
        "counterparties_resolved": "ಪರಪಕ್ಷಗಳು ಪರಿಹರಿಸಿದವು",
        "accounts_flagged": "ಗುರುತಿಸಿದ ಖಾತೆಗಳು",
        "rank": "ಶ್ರೇಣಿ",
        "score": "ಅಂಕ",
        "supporting_transactions": "ಬೆಂಬಲಿಸುವ ವ್ಯವಹಾರಗಳು",
        "date": "ದಿನಾಂಕ",
        "type": "ಪ್ರಕಾರ",
        "amount": "ಮೊತ್ತ",
        "counterparty": "ಪರಪಕ್ಷ",
        "reference": "ಉಲ್ಲೇಖ",
        "assessment": "ಮೌಲ್ಯಮಾಪನ",
        "strong_pattern_types": "ಬಲವಾದ ಮಾದರಿ ಪ್ರಕಾರ(ಗಳು)",
        "distinct_patterns": "ಪ್ರತ್ಯೇಕ ಮಾದರಿ(ಗಳು)",
        "evidence": "ಸಾಕ್ಷ್ಯ",
        "no_accounts_flagged": "ಈ ರನ್‌ನಲ್ಲಿ ತನಿಖೆಗೆ ಗುರುತಿಸುವ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸಿದ ಖಾತೆಗಳು ಇಲ್ಲ.",
        "graph_missing": "ಈ ರನ್‌ಗೆ ಈ ಗ್ರಾಫ್ ರೆಂಡರ್ ಮಾಡಲು ಸಾಕಷ್ಟು ಸಂಪರ್ಕಿತ ವ್ಯವಹಾರಗಳಿಲ್ಲ.",
        "lead_note": "ಸಾಂಖ್ಯಿಕ ಸುಳಿವುಗಳು — ಇನ್ನೂ ತಿಳಿದಿರುವ ಮಾದರಿಯೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾಗಿಲ್ಲ; ಕೈಯಾರೆ ಪರಿಶೀಲನೆ ಶಿಫಾರಸು.",
        "lead": "ಸುಳಿವು",
        "key_concern": "ಮುಖ್ಯ ಆತಂಕ",
        "score_legend": "ಅಂಕಗಳ ವಿವರಣೆ",
        "score_range": "ಅಂಕ ವ್ಯಾಪ್ತಿ",
        "what_it_means": "ಅದರ ಅರ್ಥ",
        "footer_prefix": "ರಚಿಸಿದವರು",
        "footer_suffix": "ಎಲ್ಲಾ ಕಂಡುಹಿಡಿಕೆಗಳು ಸ್ವತಂತ್ರ ಪರಿಶೀಲನೆ ಅಗತ್ಯವಿರುವ ತನಿಖಾ ಸುಳಿವುಗಳಾಗಿವೆ.",
        "report_basis_suffix": "ವ್ಯವಹಾರಗಳ ಆಧಾರದ ಮೇಲೆ, ಅವಧಿ",
        "report_basis_to": "ರಿಂದ",
        "account_s": "ಖಾತೆ(ಗಳು)",
        "edge_s": "ಎಡ್ಜ್(ಗಳು)",
        "more": "ಹೆಚ್ಚು",
        "and": "ಮತ್ತು",
        "no_graph_connections": "ಈ ರನ್‌ನಲ್ಲಿ ತನಿಖೆಗೆ ಗುರುತಿಸುವ ಮಾನದಂಡಗಳನ್ನು ಪೂರೈಸಿದ ಖಾತೆಗಳು ಇಲ್ಲ.",
        "case_narrative": "ಪ್ರಕರಣ ನಿರೂಪಣೆ",
        "case_narrative_intro": "ತನಿಖಾಧಿಕಾರಿಗಾಗಿ ಸಂಕ್ಷಿಪ್ತವಾಗಿ:",
        "total_moved_label": "ಒಟ್ಟು ವರ್ಗಾವಣೆಯಾದ ಹಣ",
        "into_network_label": "ಶಂಕಿತ ಜಾಲಕ್ಕೆ ಪ್ರವೇಶಿಸಿದ ಹಣ",
        "first_investigation_target": "ಮೊದಲು ತನಿಖೆ ಮಾಡಿ",
        "data_security": "ಡೇಟಾ ಭದ್ರತೆ ಮತ್ತು ವಿಧಾನ (ಅನುಬಂಧ)",
        "what_stays_local": "ಈ ಯಂತ್ರದಲ್ಲಿ ಉಳಿಯುವುದು",
        "what_leaves_machine": "ಬಾಹ್ಯ ಸೇವೆಗೆ ಕಳುಹಿಸುವುದು",
        "llm_usage_label": "ಈ ರನ್‌ನಲ್ಲಿ ಭಾಷಾ-ಮಾದರಿ ಕರೆಗಳು",
        "prime_suspects": "ಪ್ರಮುಖ ಶಂಕಿತರು — ಮೊದಲು ತನಿಖೆ ಮಾಡಿ",
        "prime_suspects_intro": "ಈ ಪ್ರಕರಣದ ಅತ್ಯುನ್ನತ ಆದ್ಯತೆಯ ಖಾತೆಗಳು, ಕ್ರಮದಲ್ಲಿ:",
        "priority_note_a": "ಅತ್ಯುನ್ನತ ಆದ್ಯತೆಯ",
        "priority_note_b": "ಖಾತೆಗಳನ್ನು ಸಂಪೂರ್ಣ ವಿವರದಲ್ಲಿ ತೋರಿಸಲಾಗಿದೆ. ಎಲ್ಲಾ",
        "priority_note_c": "ಗುರುತಿಸಿದ ಖಾತೆಗಳನ್ನು ಅಂತಿಮ ಸಾರಾಂಶ ಕೋಷ್ಟಕದಲ್ಲಿ ಶ್ರೇಯಾಂಕಗೊಳಿಸಲಾಗಿದೆ.",
    },
}


PATTERN_NAMES_KN: dict[str, str] = {
    "duplicate_verification": "ನಕಲು ವ್ಯವಹಾರ ಪರಿಶೀಲನೆ",
    "failed_reversed_transaction_detection": "ವಿಫಲ/ರಿವರ್ಸ್ ವ್ಯವಹಾರ ಪತ್ತೆ",
    "pass_through_routing_account": "ಪಾಸ್-ಥ್ರೂ ಅಥವಾ ರೂಟಿಂಗ್ ಖಾತೆ",
    "fund_pooling_account": "ಹಣ ಸಂಗ್ರಹಿಸುವ ಖಾತೆ",
    "structuring_smurfing_detection": "ಸಣ್ಣ ಭಾಗಗಳಾಗಿ ವಿಭಜಿಸಿದ ವ್ಯವಹಾರ ಮಾದರಿ",
    "money_flow_graph_construction": "ಹಣದ ಹರಿವು ಗ್ರಾಫ್ ನಿರ್ಮಾಣ",
    "circular_flow_multi_hop_cycle_detection": "ಬಹು ಹಂತದ ವಲಯಾಕಾರ ಹಣ ಹರಿವು",
    "money_trail_tracing": "ಹಣದ ಹಾದಿ ಅನುಸರಣೆ",
    "credit_to_cash_out_chains": "ಕ್ರೆಡಿಟ್ ನಂತರ ನಗದು ಹೊರಹಾಕುವ ಸರಣಿ",
    "cross_statement_links": "ಸ್ಟೇಟ್‌ಮೆಂಟ್‌ಗಳ ನಡುವಿನ ಸಂಪರ್ಕಗಳು",
    "balance_parking_account": "ಬ್ಯಾಲೆನ್ಸ್ ಪಾರ್ಕಿಂಗ್ ಖಾತೆ",
    "hub_ranking": "ಹೆಚ್ಚು ಸಂಪರ್ಕಗಳಿರುವ ಹಬ್ ಖಾತೆ",
    "low_value_account_testing": "ಕಡಿಮೆ ಮೊತ್ತದ ಖಾತೆ ಪರೀಕ್ಷೆ",
    "reversal_clusters": "ರಿವರ್ಸ್ ವ್ಯವಹಾರ ಕ್ಲಸ್ಟರ್‌ಗಳು",
    "round_value_debit_patterns": "ರೌಂಡ್-ವ್ಯಾಲ್ಯೂ ಡೆಬಿಟ್ ಮಾದರಿ",
    "shared_upi_identifiers": "ಹಂಚಿಕೊಂಡ UPI ಗುರುತುಗಳು",
    "round_trip_detection": "ರೌಂಡ್-ಟ್ರಿಪ್ ಹಣ ಹರಿವು",
    "dormant_reactivation": "ನಿಷ್ಕ್ರಿಯ ಖಾತೆಯ ಮರುಸಕ್ರಿಯತೆ",
    "first_contact_large_transfer": "ಮೊದಲ ಸಂಪರ್ಕದಲ್ಲೇ ದೊಡ್ಡ ವರ್ಗಾವಣೆ",
    "suspicious_account_ranking": "ಸಂದೇಹಾಸ್ಪದ ಖಾತೆ ಶ್ರೇಯಾಂಕ",
    "llm_investigated_anomalies": "LLM ಪರಿಶೀಲಿಸಿದ ಅಸಾಮಾನ್ಯ ಸುಳಿವುಗಳು",
    "ml_ensemble_anomaly_lead": "ML ಸಮೂಹ ಅಸಾಮಾನ್ಯ ಸುಳಿವು",
}


def labels(language: str | None) -> dict[str, str]:
    return LABELS[normalize_language(language)]


def pattern_display(pattern_key: str, language: str | None = "en") -> str:
    parts = str(pattern_key).split("_", 1)
    name = parts[1] if len(parts) > 1 else str(pattern_key)
    if normalize_language(language) == "kn":
        return PATTERN_NAMES_KN.get(name, name.replace("_", " "))
    return name.replace("_", " ").title()


def score_bands(language: str | None = "en") -> list[tuple[float, str, str]]:
    if normalize_language(language) == "kn":
        return [
            (600.0, "strong", "ಬಹು ಸ್ವತಂತ್ರ ಮಾದರಿ ಪ್ರಕಾರಗಳಲ್ಲಿ ಬಲವಾದ ಸಾಕ್ಷ್ಯ — ಹೆಚ್ಚಿನ ತನಿಖಾ ಆದ್ಯತೆ"),
            (300.0, "moderate", "ಮಧ್ಯಮ ಮಟ್ಟದ ಸಾಕ್ಷ್ಯ — ಮುಂದಿನ ಪರಿಶೀಲನೆಗೆ ಯೋಗ್ಯ"),
            (0.0, "weak", "ದುರ್ಬಲ ಅಥವಾ ಪ್ರತ್ಯೇಕ ಸುಳಿವುಗಳು — ಉಲ್ಲೇಖಕ್ಕಾಗಿ"),
        ]
    return [
        (600.0, "strong", "Strong evidence across multiple independent pattern types — high investigative priority"),
        (300.0, "moderate", "Moderate evidence, worth follow-up but less urgent"),
        (0.0, "weak", "Weak or isolated signals, mostly for reference"),
    ]


def graph_specs(language: str | None = "en") -> list[tuple[str, str, str]]:
    if normalize_language(language) == "kn":
        return [
            (
                "ಕೇಸ್ ಅವಲೋಕನ ಗ್ರಾಫ್",
                "report_graphs/case_overview_graph.png",
                "ಈ ಪ್ರದರ್ಶನವು ಪುನರ್‌ನಿರ್ಮಿತ ಕ್ಲಸ್ಟರ್‌ಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸುತ್ತದೆ: ಪ್ರತಿ ನೋಡ್ ಒಂದು ಕೇಸ್ ಕ್ಲಸ್ಟರ್ ಆಗಿದ್ದು, ಅಪಾಯ ಮಟ್ಟ ಮತ್ತು ಖಾತೆ/ಅಂಚು ಎಣಿಕೆಯನ್ನು ಸಾರಾಂಶಗೊಳಿಸುತ್ತದೆ.",
            ),
            (
                "ಖಾತೆಗಳ ಪರಸ್ಪರ ಸಂಪರ್ಕ ಗ್ರಾಫ್",
                "report_graphs/account_interconnection_graph.png",
                "ಈ ಸ್ಥಿರ ಪ್ರದರ್ಶನವನ್ನು ಓದಲು ಸುಲಭವಾಗುವಂತೆ ಫಿಲ್ಟರ್ ಮಾಡಲಾಗಿದೆ: ಇದು ಪ್ರಮುಖ ಖಾತೆ-ಖಾತೆ ಹಣ ಹರಿವುಗಳು ಮತ್ತು ಸಾಕ್ಷ್ಯಾತ್ಮಕ ಬಾಹ್ಯ ಪರಪಕ್ಷಗಳನ್ನು ತೋರಿಸುತ್ತದೆ; ಪೂರ್ಣ-ಸಾಂದ್ರತೆಯ ನೆಟ್‌ವರ್ಕ್ UI ಗ್ರಾಫ್ ಡೇಟಾದಲ್ಲಿ ಲಭ್ಯವಿದೆ.",
            ),
            (
                "ಸಂದೇಹಾಸ್ಪದ ಚಟುವಟಿಕೆ ಸಮಯರೇಖೆ",
                "report_graphs/suspicious_timeline.png",
                "ಗುರುತಿಸಲಾದ ಚಟುವಟಿಕೆಗಳು ತನಿಖೆಯ ಖಾತೆಗಳಾದ್ಯಂತ ಯಾವ ಸಮಯದಲ್ಲಿ ಗುಂಪುಗೊಂಡಿವೆ ಎಂಬುದನ್ನು ತೋರಿಸುತ್ತದೆ.",
            ),
            (
                "ವಂಚನೆ ಮಾದರಿ ಸಾರಾಂಶ",
                "report_graphs/fraud_pattern_summary.png",
                "ತನಿಖೆಯ ಖಾತೆಗಳಾದ್ಯಂತ ಯಾವ ವಂಚನೆ ಮಾದರಿಗಳು ಪತ್ತೆಯಾದವು ಮತ್ತು ಅವುಗಳ ಪ್ರಮಾಣವನ್ನು ತೋರಿಸುತ್ತದೆ.",
            ),
        ]
    return [
        (
            "Case Overview Graph",
            "report_graphs/case_overview_graph.png",
            "This exhibit summarizes reconstructed case clusters only: each node is a cluster with its risk level and account/edge counts, while detailed account links are shown separately for the highest-risk clusters.",
        ),
        (
            "Account Interconnection Graph",
            "report_graphs/account_interconnection_graph.png",
            "This static exhibit is filtered for legibility: it shows the material account-to-account relationships and only the most evidential external counterparties, while the full-density network remains available in the UI graph data.",
        ),
        (
            "Suspicious Activity Timeline",
            "report_graphs/suspicious_timeline.png",
            "When flagged activity clustered in time across the investigated accounts.",
        ),
        (
            "Fraud-Pattern Summary",
            "report_graphs/fraud_pattern_summary.png",
            "Which fraud patterns fired, and how often, across the investigated accounts.",
        ),
    ]


def kannada_bullet_text(pattern: str, evidence: str) -> str:
    return f"{pattern} ಸಂಬಂಧಿತ ಕಂಡುಹಿಡಿಕೆ ಕಂಡುಬಂದಿದೆ. ಸಾಕ್ಷ್ಯವನ್ನು ಬದಲಾಯಿಸದೆ ದಾಖಲಿಸಲಾಗಿದೆ: {evidence}"


def kannada_account_overview(account_id: str, score: float, strong_n: int, distinct_n: int) -> str:
    return (
        f"{account_id} ಖಾತೆಯಲ್ಲಿ {strong_n} ಬಲವಾದ ಮಾದರಿ ಪ್ರಕಾರ(ಗಳು) ಮತ್ತು "
        f"{distinct_n} ಪ್ರತ್ಯೇಕ ಮಾದರಿ(ಗಳು) ಕಂಡುಬಂದಿವೆ. ಒಟ್ಟು ಸಂಯುಕ್ತ ಸಂದೇಹ ಅಂಕ {round(score)} ಆಗಿದೆ."
    )


def kannada_case_summary(cluster_count: int, suspicious_count: int, top_cluster: str, top_score: float) -> str:
    if not cluster_count:
        return "ಈ ರನ್‌ನಲ್ಲಿ ವ್ಯವಹಾರಾಧಾರಿತ ಖಾತೆ ಕ್ಲಸ್ಟರ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ."
    return (
        f"ಪ್ರಕರಣದಲ್ಲಿ {cluster_count} ಖಾತೆ ಕ್ಲಸ್ಟರ್(ಗಳು) ಇವೆ ಮತ್ತು "
        f"{suspicious_count} ಖಾತೆ(ಗಳು) ಸಂದೇಹಾಸ್ಪದ ಚಟುವಟಿಕೆಗಾಗಿ ಶ್ರೇಯಾಂಕಗೊಂಡಿವೆ. "
        f"ಅತ್ಯುನ್ನತ ಆದ್ಯತೆಯ ಕ್ಲಸ್ಟರ್ {top_cluster} ಆಗಿದ್ದು, ಒಟ್ಟು ಅಂಕ {top_score:.2f}."
    )
